Repository Team-RunningTomato/Team-RunningTomato-Running-Tomato-BackEnd, pull requests merged in 2024-12, with the labels that each got.

#14 🔀 :: 로그아웃 기능
  src/main/java/com/tomato/running/domain/auth/presentation/AuthController.java
  src/main/java/com/tomato/running/domain/auth/repository/RefreshTokenRepository.java
  src/main/java/com/tomato/running/domain/auth/service/LoginService.java
  src/main/java/com/tomato/running/domain/auth/service/LogoutService.java
  src/main/java/com/tomato/running/domain/auth/service/ReissueTokenService.java
  src/main/java/com/tomato/running/global/security/config/SecurityConfig.java
  src/main/java/com/tomato/running/global/security/util/count/RefreshToken.java
Labels: 1️⃣Priority: High, ✨ Feature

#16 🔀 :: 쿠키 생성 기능
  build.gradle.kts
  src/main/java/com/tomato/running/domain/auth/presentation/AuthController.java
  src/main/java/com/tomato/running/global/security/util/count/CookieUtil.java
Labels: ✨ Feature

#18 🔀 :: ERD에 맞춰 엔티티 수정
  src/main/java/com/tomato/running/domain/auth/service/LoginService.java
  src/main/java/com/tomato/running/domain/month/EndLocation.java
  src/main/java/com/tomato/running/domain/month/Month.java
  src/main/java/com/tomato/running/domain/month/StartLocation.java
  src/main/java/com/tomato/running/domain/user/User.java
  src/main/java/com/tomato/running/global/oauth/dto/NaverInfoResponse.java
Labels: 1️⃣Priority: High

#20 🔀 :: 유저 정보 조회 api
  src/main/java/com/tomato/running/domain/auth/service/LoginService.java
  src/main/java/com/tomato/running/domain/run/EndLocation.java
  src/main/java/com/tomato/running/domain/run/Run.java
  src/main/java/com/tomato/running/domain/run/StartLocation.java
  src/main/java/com/tomato/running/domain/run/repository/RunRepository.java
  src/main/java/com/tomato/running/domain/running/RunningUser.java
  src/main/java/com/tomato/running/domain/running/exception/RunningUserNotFoundException.java
  src/main/java/com/tomato/running/domain/running/repository/RunningUserRepository.java
  src/main/java/com/tomato/running/domain/user/controller/UserController.java
  src/main/java/com/tomato/running/domain/user/controller/data/res/GetMyInformationResponseDto.java
  src/main/java/com/tomato/running/domain/user/service/GetMyInformationService.java
  src/main/java/com/tomato/running/global/error/ErrorCode.java
  src/main/java/com/tomato/running/global/security/config/SecurityConfig.java
Labels: 1️⃣Priority: High, ✨ Feature

#22 런닝 회원 모집 api
  src/main/java/com/tomato/running/domain/meeting/Meeting.java
  src/main/java/com/tomato/running/domain/meeting/controller/MeetingController.java
  src/main/java/com/tomato/running/domain/meeting/controller/data/req/CreateMeetingRequestDto.java
  src/main/java/com/tomato/running/domain/meeting/repository/MeetingRepository.java
  src/main/java/com/tomato/running/domain/meeting/service/CreateMeetingService.java
  src/main/java/com/tomato/running/domain/run/EndLocation.java
  src/main/java/com/tomato/running/domain/run/StartLocation.java
  src/main/java/com/tomato/running/global/security/config/SecurityConfig.java
Labels: ✨ Feature

#24 🔀 :: 런닝 모집글 리스트 불러오기
  src/main/java/com/tomato/running/domain/auth/service/LoginService.java
  src/main/java/com/tomato/running/domain/meeting/controller/MeetingController.java
  src/main/java/com/tomato/running/domain/meeting/controller/data/res/GetMeetingResponseDto.java
  src/main/java/com/tomato/running/domain/meeting/service/GetMeetingListService.java
  src/main/java/com/tomato/running/domain/running/RunningUser.java
  src/main/java/com/tomato/running/domain/running/repository/RunningUserRepository.java
  src/main/java/com/tomato/running/domain/user/User.java
  src/main/java/com/tomato/running/domain/user/service/GetMyInformationService.java
  src/main/java/com/tomato/running/global/security/config/SecurityConfig.java
Labels: 1️⃣Priority: High, ✨ Feature

#26 🔀 :: 런닝 모집글 상세보기
  src/main/java/com/tomato/running/domain/auth/service/LoginService.java
  src/main/java/com/tomato/running/domain/meeting/controller/MeetingController.java
  src/main/java/com/tomato/running/domain/meeting/controller/data/res/GetMeetingInfoResponseDto.java
  src/main/java/com/tomato/running/domain/meeting/exception/MeetingNotFoundException.java
  src/main/java/com/tomato/running/domain/meeting/repository/MeetingMemberRepository.java
  src/main/java/com/tomato/running/domain/meeting/service/GetMeetingInfoService.java
  src/main/java/com/tomato/running/domain/user/User.java
  src/main/java/com/tomato/running/global/error/ErrorCode.java
  src/main/java/com/tomato/running/global/security/config/SecurityConfig.java
  src/test/java/com/tomato/running/RunningApplicationTests.java
Labels: 1️⃣Priority: High, ✨ Feature

#28 🔀 :: 런닝 모집글 수정
  src/main/java/com/tomato/running/domain/meeting/Meeting.java
  src/main/java/com/tomato/running/domain/meeting/controller/MeetingController.java
  src/main/java/com/tomato/running/domain/meeting/exception/AuthorNotValidException.java
  src/main/java/com/tomato/running/domain/meeting/service/UpdateMeetingService.java
  src/main/java/com/tomato/running/global/error/ErrorCode.java
  src/main/java/com/tomato/running/global/security/config/SecurityConfig.java
Labels: ✨ Feature

#30 🔀 :: 런닝 모집글 삭제
  src/main/java/com/tomato/running/domain/meeting/controller/MeetingController.java
  src/main/java/com/tomato/running/domain/meeting/service/DeleteMeetingService.java
  src/main/java/com/tomato/running/global/security/config/SecurityConfig.java
Labels: ✨ Feature

#35 🔀 :: 런닝 기록 측정
  src/main/java/com/tomato/running/domain/auth/service/LoginService.java
  src/main/java/com/tomato/running/domain/meeting/MeetingMember.java
  src/main/java/com/tomato/running/domain/meeting/service/GetMeetingInfoService.java
  src/main/java/com/tomato/running/domain/run/Run.java
  src/main/java/com/tomato/running/domain/run/exception/InvalidRunDistanceException.java
  src/main/java/com/tomato/running/domain/run/presentation/RunController.java
  src/main/java/com/tomato/running/domain/run/presentation/data/req/RecordRunningRequestDto.java
  src/main/java/com/tomato/running/domain/run/service/RecordRunningService.java
  src/main/java/com/tomato/running/domain/run/util/LevelUtil.java
  src/main/java/com/tomato/running/domain/running/RunningUser.java
  src/main/java/com/tomato/running/domain/user/User.java
  src/main/java/com/tomato/running/domain/user/controller/data/res/GetMyInformationResponseDto.java
  src/main/java/com/tomato/running/global/error/ErrorCode.java
  src/main/java/com/tomato/running/global/security/config/SecurityConfig.java
Labels: 1️⃣Priority: High, ✨ Feature

#36 🔀 :: 런닝 모집글 검색
  src/main/java/com/tomato/running/domain/meeting/controller/MeetingController.java
  src/main/java/com/tomato/running/domain/meeting/repository/MeetingRepository.java
  src/main/java/com/tomato/running/domain/meeting/service/GetSearchMeetingService.java
  src/main/java/com/tomato/running/global/security/config/SecurityConfig.java
Labels: ✨ Feature

#40 🔀 :: 내가 신청한 런닝 구인글 가져오기
  src/main/java/com/tomato/running/domain/meeting/repository/MeetingMemberRepository.java
  src/main/java/com/tomato/running/domain/user/controller/UserController.java
  src/main/java/com/tomato/running/domain/user/service/GetMyApplicationMeetingService.java
  src/main/java/com/tomato/running/global/security/config/SecurityConfig.java
  src/main/java/com/tomato/running/global/security/jwt/TokenProvider.java
Labels: ✨ Feature

#42 🔀 :: 파일 패키지로 정리
  src/main/java/com/tomato/running/domain/auth/service/LoginService.java
  src/main/java/com/tomato/running/domain/auth/service/LogoutService.java
  src/main/java/com/tomato/running/domain/meeting/controller/data/res/GetMeetingInfoResponseDto.java
  src/main/java/com/tomato/running/domain/meeting/controller/data/res/GetMeetingResponseDto.java
  src/main/java/com/tomato/running/domain/meeting/entity/Meeting.java
  src/main/java/com/tomato/running/domain/meeting/entity/MeetingMember.java
  src/main/java/com/tomato/running/domain/meeting/repository/MeetingMemberRepository.java
  src/main/java/com/tomato/running/domain/meeting/repository/MeetingRepository.java
  src/main/java/com/tomato/running/domain/meeting/service/CreateMeetingService.java
  src/main/java/com/tomato/running/domain/meeting/service/DeleteMeetingService.java
  src/main/java/com/tomato/running/domain/meeting/service/GetMeetingInfoService.java
  src/main/java/com/tomato/running/domain/meeting/service/GetSearchMeetingService.java
  src/main/java/com/tomato/running/domain/meeting/service/UpdateMeetingService.java
  src/main/java/com/tomato/running/domain/run/entity/EndLocation.java
  src/main/java/com/tomato/running/domain/run/entity/Run.java
  src/main/java/com/tomato/running/domain/run/entity/StartLocation.java
  src/main/java/com/tomato/running/domain/run/repository/RunRepository.java
  src/main/java/com/tomato/running/domain/run/service/RecordRunningService.java
  src/main/java/com/tomato/running/domain/running/entity/RunningUser.java
  src/main/java/com/tomato/running/domain/running/repository/RunningUserRepository.java
  src/main/java/com/tomato/running/domain/user/entity/Role.java
  src/main/java/com/tomato/running/domain/user/entity/User.java
  src/main/java/com/tomato/running/domain/user/repository/UserRepository.java
  src/main/java/com/tomato/running/domain/user/service/GetMeetingsService.java
  src/main/java/com/tomato/running/domain/user/service/GetMyApplicationMeetingService.java
  src/main/java/com/tomato/running/domain/user/service/GetMyInformationService.java
  src/main/java/com/tomato/running/domain/user/service/UpdateWeightAndHeightService.java
  src/main/java/com/tomato/running/domain/user/util/UserUtil.java
  src/main/java/com/tomato/running/global/auth/AuthDetails.java
  src/main/java/com/tomato/running/global/security/auth/PrincipalDetails.java
  src/main/java/com/tomato/running/global/security/auth/PrincipalDetailsService.java
Labels: 2️⃣Priority: Medium

#46 🔀 :: 런닝 모집글 취소
  src/main/java/com/tomato/running/domain/meeting/controller/MeetingController.java
  src/main/java/com/tomato/running/domain/meeting/exception/MemberNotValidException.java
  src/main/java/com/tomato/running/domain/meeting/repository/MeetingMemberRepository.java
  src/main/java/com/tomato/running/domain/meeting/service/DeleteApplicationMeetingService.java
  src/main/java/com/tomato/running/global/error/ErrorCode.java
  src/main/java/com/tomato/running/global/security/config/SecurityConfig.java
Labels: ✨ Feature

#48 🔀 :: 런닝 모집 글 추가 api 수정
  src/main/java/com/tomato/running/domain/meeting/controller/data/req/CreateMeetingRequestDto.java
  src/main/java/com/tomato/running/domain/meeting/controller/data/res/GetMeetingInfoResponseDto.java
  src/main/java/com/tomato/running/domain/meeting/entity/Meeting.java
  src/main/java/com/tomato/running/domain/meeting/service/CreateMeetingService.java
  src/main/java/com/tomato/running/domain/meeting/service/GetMeetingInfoService.java
  src/main/java/com/tomato/running/domain/meeting/service/UpdateMeetingService.java
Labels: 1️⃣Priority: High

#50 🔀 :: 토큰 재발급 api 오류 수정
  src/main/java/com/tomato/running/domain/auth/service/ReissueTokenService.java
  src/main/java/com/tomato/running/global/error/CustomException.java
  src/main/java/com/tomato/running/global/security/jwt/TokenProvider.java
  src/main/java/com/tomato/running/global/security/util/count/RefreshToken.java
Labels: 0️⃣Priority: Critical, 🐞 BugFix

#52 🔀 :: 런닝글에 대한 런닝 처리 수정
  src/main/java/com/tomato/running/domain/auth/service/LoginService.java
  src/main/java/com/tomato/running/domain/meeting/entity/Meeting.java
  src/main/java/com/tomato/running/domain/meeting/entity/MeetingMember.java
  src/main/java/com/tomato/running/domain/meeting/repository/MeetingMemberRepository.java
  src/main/java/com/tomato/running/domain/meeting/service/ApplicationMeetingService.java
  src/main/java/com/tomato/running/domain/meeting/service/CreateMeetingService.java
  src/main/java/com/tomato/running/domain/meeting/service/GetMeetingInfoService.java
  src/main/java/com/tomato/running/domain/run/entity/Run.java
  src/main/java/com/tomato/running/domain/run/exception/MeetingMemberNotFoundException.java
  src/main/java/com/tomato/running/domain/run/presentation/RunController.java
  src/main/java/com/tomato/running/domain/run/presentation/data/req/RecordRunningRequestDto.java
  src/main/java/com/tomato/running/domain/run/service/RecordRunningService.java
  src/main/java/com/tomato/running/domain/running/entity/RunningUser.java
  src/main/java/com/tomato/running/domain/running/repository/RunningUserRepository.java
  src/main/java/com/tomato/running/domain/user/entity/User.java
  src/main/java/com/tomato/running/domain/user/presentation/UserController.java
  src/main/java/com/tomato/running/domain/user/presentation/data/req/UpdateWeightAndHeightRequestDto.java
  src/main/java/com/tomato/running/domain/user/presentation/data/res/GetMyInformationResponseDto.java
  src/main/java/com/tomato/running/domain/user/service/GetMyInformationService.java
  src/main/java/com/tomato/running/domain/user/service/UpdateWeightAndHeightService.java
  src/main/java/com/tomato/running/global/error/ErrorCode.java
  src/main/java/com/tomato/running/global/security/config/SecurityConfig.java
Labels: 1️⃣Priority: High, 📬 API

#54 🔀 :: 회원정보 api 수정
  src/main/java/com/tomato/running/domain/user/presentation/data/res/GetMyInformationResponseDto.java
  src/main/java/com/tomato/running/domain/user/service/GetMyInformationService.java
Labels: ✨ Feature

#56 🔀 :: 클라이언트 CORS 이슈 해결
  src/main/java/com/tomato/running/global/security/config/CorsConfig.java
Labels: 1️⃣Priority: High

#58 🔀 :: 회원 정보 불러오기 필드 네임 변경
  src/main/java/com/tomato/running/domain/user/presentation/data/res/GetMyInformationResponseDto.java
  src/main/java/com/tomato/running/domain/user/service/GetMyInformationService.java
Labels: 1️⃣Priority: High
