Repository Team-RunningTomato/Team-RunningTomato-Running-Tomato-BackEnd, pull requests merged in 2024-11, with the labels that each got.

#6 Naver Oauth 구현
  build.gradle.kts
  src/main/java/com/tomato/running/domain/auth/presentation/AuthController.java
  src/main/java/com/tomato/running/domain/auth/presentation/data/res/TokenDto.java
  src/main/java/com/tomato/running/domain/auth/service/LoginService.java
  src/main/java/com/tomato/running/domain/meeting/Meeting.java
  src/main/java/com/tomato/running/domain/meeting/MeetingMember.java
  src/main/java/com/tomato/running/domain/month/Month.java
  src/main/java/com/tomato/running/domain/user/Role.java
  src/main/java/com/tomato/running/domain/user/User.java
  src/main/java/com/tomato/running/domain/user/exception/UserNotFoundException.java
  src/main/java/com/tomato/running/domain/user/repository/UserRepository.java
  src/main/java/com/tomato/running/global/error/CustomException.java
  src/main/java/com/tomato/running/global/error/CustomExceptionHandler.java
  src/main/java/com/tomato/running/global/error/ErrorCode.java
  src/main/java/com/tomato/running/global/error/ErrorResponseEntity.java
  src/main/java/com/tomato/running/global/oauth/NaverApiClient.java
  src/main/java/com/tomato/running/global/oauth/OAuthProvider.java
  src/main/java/com/tomato/running/global/oauth/config/ClientConfig.java
  src/main/java/com/tomato/running/global/oauth/dto/NaverInfoResponse.java
  src/main/java/com/tomato/running/global/oauth/dto/NaverLoginParams.java
  src/main/java/com/tomato/running/global/oauth/dto/NaverTokens.java
  src/main/java/com/tomato/running/global/oauth/service/RequestOAuthInfoService.java
  src/main/java/com/tomato/running/global/security/auth/PrincipalDetails.java
  src/main/java/com/tomato/running/global/security/auth/PrincipalDetailsService.java
  src/main/java/com/tomato/running/global/security/config/CorsConfig.java
  src/main/java/com/tomato/running/global/security/config/JwtSecurityConfig.java
  src/main/java/com/tomato/running/global/security/config/SecurityConfig.java
  src/main/java/com/tomato/running/global/security/exception/TokenExpirationException.java
  src/main/java/com/tomato/running/global/security/exception/TokenNotValidException.java
  src/main/java/com/tomato/running/global/security/handler/JwtAccessDeniedHandle.java
  src/main/java/com/tomato/running/global/security/handler/JwtAuthenticationEntryPoint.java
  src/main/java/com/tomato/running/global/security/jwt/JwtFilter.java
  src/main/java/com/tomato/running/global/security/jwt/TokenProvider.java
  src/main/resources/application.properties
  src/main/resources/application.yml
Labels: ✨ Feature

#8 🔀 :: 토큰 재발급
  .gitignore
  build.gradle.kts
  src/main/java/com/tomato/running/domain/auth/exception/TokenNotFoundException.java
  src/main/java/com/tomato/running/domain/auth/presentation/AuthController.java
  src/main/java/com/tomato/running/domain/auth/repository/RefreshTokenRepository.java
  src/main/java/com/tomato/running/domain/auth/service/LoginService.java
  src/main/java/com/tomato/running/domain/auth/service/ReissueTokenService.java
  src/main/java/com/tomato/running/global/annotation/ReadOnlyTransactionService.java
  src/main/java/com/tomato/running/global/annotation/TransactionService.java
  src/main/java/com/tomato/running/global/error/ErrorCode.java
  src/main/java/com/tomato/running/global/error/ErrorResponseEntity.java
  src/main/java/com/tomato/running/global/security/jwt/TokenProvider.java
  src/main/java/com/tomato/running/global/security/util/count/RefreshToken.java
Labels: 1️⃣Priority: High, ✨ Feature

#10 🔀 :: Redis yml 연결
  src/main/java/com/tomato/running/global/redis/RedisConfig.java
  src/main/java/com/tomato/running/global/security/util/count/RefreshToken.java
  src/main/resources/application.yml
Labels: 1️⃣Priority: High

#12 🔀 :: 키, 몸무게 추가 입력 api
  build.gradle.kts
  src/main/java/com/tomato/running/domain/user/User.java
  src/main/java/com/tomato/running/domain/user/controller/UserController.java
  src/main/java/com/tomato/running/domain/user/controller/data/req/UpdateWeightAndHeightRequestDto.java
  src/main/java/com/tomato/running/domain/user/repository/UserRepository.java
  src/main/java/com/tomato/running/domain/user/service/UpdateWeightAndHeightService.java
  src/main/java/com/tomato/running/domain/user/util/UserUtil.java
  src/main/java/com/tomato/running/global/auth/AuthDetails.java
  src/main/java/com/tomato/running/global/auth/AuthDetailsService.java
  src/main/java/com/tomato/running/global/security/config/SecurityConfig.java
  src/main/java/com/tomato/running/global/security/jwt/TokenProvider.java
Labels: 1️⃣Priority: High, ✨ Feature
